export const initialNode = [
  {
    id: "0",
    type: "profileNode",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      parent: true,
      partner: true,
      expartner: false,
      children: 1,
      exchildren: 0,
      childNodes: [
        {
          id: "3",
          type: "profileNode",
          position: {
            x: 150,
            y: 380,
          },
          data: {
            parent: true,
            partner: false,
            expartner: false,
            children: 0,
            exchildren: 0,
            childNodes: [],
            exchildNodes: [],
            parentNode: {
              id: "0",
              type: "profileNode",
              position: {
                x: 0,
                y: 0,
              },
              data: {
                parent: true,
                partner: true,
                expartner: false,
                children: 0,
                exchildren: 0,
                childNodes: [],
                exchildNodes: [],
                parentNode: {
                  id: "1",
                  type: "profileNode",
                  position: {
                    x: 150,
                    y: -380,
                  },
                  data: {
                    parent: false,
                    partner: true,
                    expartner: false,
                    children: 2,
                    exchildren: 0,
                    childNodes: [
                      {
                        parent: false,
                        partner: false,
                        expartner: false,
                        children: 0,
                        exchildren: 0,
                        childNodes: [],
                        exchildNodes: [],
                        parentNode: [],
                        gender: "female",
                        position: {
                          x: 0,
                          y: 0,
                        },
                      },
                      {
                        id: "2",
                        type: "profileNode",
                        position: {
                          x: -300,
                          y: 0,
                        },
                        data: {
                          parent: true,
                          partner: false,
                          expartner: false,
                          children: 0,
                          exchildren: 0,
                          childNodes: [],
                          exchildNodes: [],
                          parentNode: [],
                          gender: "female",
                          position: {
                            x: -300,
                            y: 0,
                          },
                        },
                      },
                    ],
                    exchildNodes: [],
                    parentNode: [],
                    gender: "female",
                    position: {
                      x: 150,
                      y: -380,
                    },
                  },
                },
                gender: "male",
                position: {
                  x: 0,
                  y: 0,
                },
              },
            },
            gender: "female",
            position: {
              x: 150,
              y: 380,
            },
          },
        },
      ],
      exchildNodes: [],
      parentNode: {
        id: "1",
        type: "profileNode",
        position: {
          x: 150,
          y: -380,
        },
        data: {
          parent: false,
          partner: true,
          expartner: false,
          children: 2,
          exchildren: 0,
          childNodes: [
            {
              parent: false,
              partner: false,
              expartner: false,
              children: 0,
              exchildren: 0,
              childNodes: [],
              exchildNodes: [],
              parentNode: [],
              gender: "female",
              position: {
                x: 0,
                y: 0,
              },
            },
            {
              id: "2",
              type: "profileNode",
              position: {
                x: -300,
                y: 0,
              },
              data: {
                parent: true,
                partner: false,
                expartner: false,
                children: 0,
                exchildren: 0,
                childNodes: [],
                exchildNodes: [],
                parentNode: [],
                gender: "female",
                position: {
                  x: -300,
                  y: 0,
                },
              },
            },
          ],
          exchildNodes: [],
          parentNode: [],
          gender: "female",
          position: {
            x: 150,
            y: -380,
          },
        },
      },
      gender: "male",
      position: {
        x: 0,
        y: 0,
      },
    },
  },
  {
    id: "1",
    type: "profileNode",
    position: {
      x: 150,
      y: -380,
    },
    data: {
      parent: false,
      partner: true,
      expartner: false,
      children: 2,
      exchildren: 0,
      childNodes: [
        {
          parent: false,
          partner: false,
          expartner: false,
          children: 0,
          exchildren: 0,
          childNodes: [],
          exchildNodes: [],
          parentNode: [],
          gender: "female",
          position: {
            x: 0,
            y: 0,
          },
        },
        {
          id: "2",
          type: "profileNode",
          position: {
            x: -300,
            y: 0,
          },
          data: {
            parent: true,
            partner: false,
            expartner: false,
            children: 0,
            exchildren: 0,
            childNodes: [],
            exchildNodes: [],
            parentNode: [],
            gender: "female",
            position: {
              x: -300,
              y: 0,
            },
          },
        },
      ],
      exchildNodes: [],
      parentNode: [],
      gender: "female",
      position: {
        x: 150,
        y: -380,
      },
    },
  },
  {
    id: "1-partner",
    type: "relationNode",
    position: {
      x: -150,
      y: -380,
    },
    data: {
      gender: "male",
    },
  },
  {
    id: "2",
    type: "profileNode",
    position: {
      x: -300,
      y: 0,
    },
    data: {
      parent: true,
      partner: true,
      expartner: false,
      children: 0,
      exchildren: 0,
      childNodes: [],
      exchildNodes: [],
      parentNode: {
        id: "1",
        type: "profileNode",
        position: {
          x: 150,
          y: -380,
        },
        data: {
          parent: false,
          partner: true,
          expartner: false,
          children: 2,
          exchildren: 0,
          childNodes: [
            {
              parent: false,
              partner: false,
              expartner: false,
              children: 0,
              exchildren: 0,
              childNodes: [],
              exchildNodes: [],
              parentNode: [],
              gender: "female",
              position: {
                x: 0,
                y: 0,
              },
            },
            {
              id: "2",
              type: "profileNode",
              position: {
                x: -300,
                y: 0,
              },
              data: {
                parent: true,
                partner: false,
                expartner: false,
                children: 0,
                exchildren: 0,
                childNodes: [],
                exchildNodes: [],
                parentNode: [],
                gender: "female",
                position: {
                  x: -300,
                  y: 0,
                },
              },
            },
          ],
          exchildNodes: [],
          parentNode: [],
          gender: "female",
          position: {
            x: 150,
            y: -380,
          },
        },
      },
      gender: "female",
      position: {
        x: -300,
        y: 0,
      },
    },
  },
  {
    id: "0-partner",
    type: "relationNode",
    position: {
      x: 300,
      y: 0,
    },
    data: {
      gender: "female",
    },
  },
  {
    id: "2-partner",
    type: "relationNode",
    position: {
      x: -600,
      y: 0,
    },
    data: {
      gender: "male",
    },
  },
  {
    id: "3",
    type: "profileNode",
    position: {
      x: 150,
      y: 380,
    },
    data: {
      parent: true,
      partner: true,
      expartner: false,
      children: 1,
      exchildren: 0,
      childNodes: [
        {
          id: "4",
          type: "profileNode",
          position: {
            x: 0,
            y: 760,
          },
          data: {
            parent: true,
            partner: false,
            expartner: false,
            children: 0,
            exchildren: 0,
            childNodes: [],
            exchildNodes: [],
            parentNode: {
              id: "3",
              type: "profileNode",
              position: {
                x: 150,
                y: 380,
              },
              data: {
                parent: true,
                partner: true,
                expartner: false,
                children: 0,
                exchildren: 0,
                childNodes: [],
                exchildNodes: [],
                parentNode: {
                  id: "0",
                  type: "profileNode",
                  position: {
                    x: 0,
                    y: 0,
                  },
                  data: {
                    parent: true,
                    partner: true,
                    expartner: false,
                    children: 0,
                    exchildren: 0,
                    childNodes: [],
                    exchildNodes: [],
                    parentNode: {
                      id: "1",
                      type: "profileNode",
                      position: {
                        x: 150,
                        y: -380,
                      },
                      data: {
                        parent: false,
                        partner: true,
                        expartner: false,
                        children: 2,
                        exchildren: 0,
                        childNodes: [
                          {
                            parent: false,
                            partner: false,
                            expartner: false,
                            children: 0,
                            exchildren: 0,
                            childNodes: [],
                            exchildNodes: [],
                            parentNode: [],
                            gender: "female",
                            position: {
                              x: 0,
                              y: 0,
                            },
                          },
                          {
                            id: "2",
                            type: "profileNode",
                            position: {
                              x: -300,
                              y: 0,
                            },
                            data: {
                              parent: true,
                              partner: false,
                              expartner: false,
                              children: 0,
                              exchildren: 0,
                              childNodes: [],
                              exchildNodes: [],
                              parentNode: [],
                              gender: "female",
                              position: {
                                x: -300,
                                y: 0,
                              },
                            },
                          },
                        ],
                        exchildNodes: [],
                        parentNode: [],
                        gender: "female",
                        position: {
                          x: 150,
                          y: -380,
                        },
                      },
                    },
                    gender: "male",
                    position: {
                      x: 0,
                      y: 0,
                    },
                  },
                },
                gender: "female",
                position: {
                  x: 150,
                  y: 380,
                },
              },
            },
            gender: "female",
            position: {
              x: 0,
              y: 760,
            },
          },
        },
      ],
      exchildNodes: [],
      parentNode: {
        id: "0",
        type: "profileNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          parent: true,
          partner: true,
          expartner: false,
          children: 0,
          exchildren: 0,
          childNodes: [],
          exchildNodes: [],
          parentNode: {
            id: "1",
            type: "profileNode",
            position: {
              x: 150,
              y: -380,
            },
            data: {
              parent: false,
              partner: true,
              expartner: false,
              children: 2,
              exchildren: 0,
              childNodes: [
                {
                  parent: false,
                  partner: false,
                  expartner: false,
                  children: 0,
                  exchildren: 0,
                  childNodes: [],
                  exchildNodes: [],
                  parentNode: [],
                  gender: "female",
                  position: {
                    x: 0,
                    y: 0,
                  },
                },
                {
                  id: "2",
                  type: "profileNode",
                  position: {
                    x: -300,
                    y: 0,
                  },
                  data: {
                    parent: true,
                    partner: false,
                    expartner: false,
                    children: 0,
                    exchildren: 0,
                    childNodes: [],
                    exchildNodes: [],
                    parentNode: [],
                    gender: "female",
                    position: {
                      x: -300,
                      y: 0,
                    },
                  },
                },
              ],
              exchildNodes: [],
              parentNode: [],
              gender: "female",
              position: {
                x: 150,
                y: -380,
              },
            },
          },
          gender: "male",
          position: {
            x: 0,
            y: 0,
          },
        },
      },
      gender: "female",
      position: {
        x: 150,
        y: 380,
      },
    },
  },
  {
    id: "3-partner",
    type: "relationNode",
    position: {
      x: -150,
      y: 380,
    },
    data: {
      gender: "male",
    },
  },
  {
    id: "4",
    type: "profileNode",
    position: {
      x: 0,
      y: 760,
    },
    data: {
      parent: true,
      partner: true,
      expartner: false,
      children: 1,
      exchildren: 0,
      childNodes: [
        {
          id: "5",
          type: "profileNode",
          position: {
            x: -150,
            y: 1140,
          },
          data: {
            parent: true,
            partner: false,
            expartner: false,
            children: 0,
            exchildren: 0,
            childNodes: [],
            exchildNodes: [],
            parentNode: {
              id: "4",
              type: "profileNode",
              position: {
                x: 0,
                y: 760,
              },
              data: {
                parent: true,
                partner: true,
                expartner: false,
                children: 0,
                exchildren: 0,
                childNodes: [],
                exchildNodes: [],
                parentNode: {
                  id: "3",
                  type: "profileNode",
                  position: {
                    x: 150,
                    y: 380,
                  },
                  data: {
                    parent: true,
                    partner: true,
                    expartner: false,
                    children: 0,
                    exchildren: 0,
                    childNodes: [],
                    exchildNodes: [],
                    parentNode: {
                      id: "0",
                      type: "profileNode",
                      position: {
                        x: 0,
                        y: 0,
                      },
                      data: {
                        parent: true,
                        partner: true,
                        expartner: false,
                        children: 0,
                        exchildren: 0,
                        childNodes: [],
                        exchildNodes: [],
                        parentNode: {
                          id: "1",
                          type: "profileNode",
                          position: {
                            x: 150,
                            y: -380,
                          },
                          data: {
                            parent: false,
                            partner: true,
                            expartner: false,
                            children: 2,
                            exchildren: 0,
                            childNodes: [
                              {
                                parent: false,
                                partner: false,
                                expartner: false,
                                children: 0,
                                exchildren: 0,
                                childNodes: [],
                                exchildNodes: [],
                                parentNode: [],
                                gender: "female",
                                position: {
                                  x: 0,
                                  y: 0,
                                },
                              },
                              {
                                id: "2",
                                type: "profileNode",
                                position: {
                                  x: -300,
                                  y: 0,
                                },
                                data: {
                                  parent: true,
                                  partner: false,
                                  expartner: false,
                                  children: 0,
                                  exchildren: 0,
                                  childNodes: [],
                                  exchildNodes: [],
                                  parentNode: [],
                                  gender: "female",
                                  position: {
                                    x: -300,
                                    y: 0,
                                  },
                                },
                              },
                            ],
                            exchildNodes: [],
                            parentNode: [],
                            gender: "female",
                            position: {
                              x: 150,
                              y: -380,
                            },
                          },
                        },
                        gender: "male",
                        position: {
                          x: 0,
                          y: 0,
                        },
                      },
                    },
                    gender: "female",
                    position: {
                      x: 150,
                      y: 380,
                    },
                  },
                },
                gender: "female",
                position: {
                  x: 0,
                  y: 760,
                },
              },
            },
            gender: "female",
            position: {
              x: -150,
              y: 1140,
            },
          },
        },
      ],
      exchildNodes: [],
      parentNode: {
        id: "3",
        type: "profileNode",
        position: {
          x: 150,
          y: 380,
        },
        data: {
          parent: true,
          partner: true,
          expartner: false,
          children: 0,
          exchildren: 0,
          childNodes: [],
          exchildNodes: [],
          parentNode: {
            id: "0",
            type: "profileNode",
            position: {
              x: 0,
              y: 0,
            },
            data: {
              parent: true,
              partner: true,
              expartner: false,
              children: 0,
              exchildren: 0,
              childNodes: [],
              exchildNodes: [],
              parentNode: {
                id: "1",
                type: "profileNode",
                position: {
                  x: 150,
                  y: -380,
                },
                data: {
                  parent: false,
                  partner: true,
                  expartner: false,
                  children: 2,
                  exchildren: 0,
                  childNodes: [
                    {
                      parent: false,
                      partner: false,
                      expartner: false,
                      children: 0,
                      exchildren: 0,
                      childNodes: [],
                      exchildNodes: [],
                      parentNode: [],
                      gender: "female",
                      position: {
                        x: 0,
                        y: 0,
                      },
                    },
                    {
                      id: "2",
                      type: "profileNode",
                      position: {
                        x: -300,
                        y: 0,
                      },
                      data: {
                        parent: true,
                        partner: false,
                        expartner: false,
                        children: 0,
                        exchildren: 0,
                        childNodes: [],
                        exchildNodes: [],
                        parentNode: [],
                        gender: "female",
                        position: {
                          x: -300,
                          y: 0,
                        },
                      },
                    },
                  ],
                  exchildNodes: [],
                  parentNode: [],
                  gender: "female",
                  position: {
                    x: 150,
                    y: -380,
                  },
                },
              },
              gender: "male",
              position: {
                x: 0,
                y: 0,
              },
            },
          },
          gender: "female",
          position: {
            x: 150,
            y: 380,
          },
        },
      },
      gender: "female",
      position: {
        x: 0,
        y: 760,
      },
    },
  },
  {
    id: "4-partner",
    type: "relationNode",
    position: {
      x: -300,
      y: 760,
    },
    data: {
      gender: "male",
    },
  },
  {
    id: "5",
    type: "profileNode",
    position: {
      x: -150,
      y: 1140,
    },
    data: {
      parent: true,
      partner: true,
      expartner: false,
      children: 1,
      exchildren: 0,
      childNodes: [
        {
          id: "6",
          type: "profileNode",
          position: {
            x: -300,
            y: 1520,
          },
          data: {
            parent: true,
            partner: false,
            expartner: false,
            children: 0,
            exchildren: 0,
            childNodes: [],
            exchildNodes: [],
            parentNode: {
              id: "5",
              type: "profileNode",
              position: {
                x: -150,
                y: 1140,
              },
              data: {
                parent: true,
                partner: true,
                expartner: false,
                children: 0,
                exchildren: 0,
                childNodes: [],
                exchildNodes: [],
                parentNode: {
                  id: "4",
                  type: "profileNode",
                  position: {
                    x: 0,
                    y: 760,
                  },
                  data: {
                    parent: true,
                    partner: true,
                    expartner: false,
                    children: 0,
                    exchildren: 0,
                    childNodes: [],
                    exchildNodes: [],
                    parentNode: {
                      id: "3",
                      type: "profileNode",
                      position: {
                        x: 150,
                        y: 380,
                      },
                      data: {
                        parent: true,
                        partner: true,
                        expartner: false,
                        children: 0,
                        exchildren: 0,
                        childNodes: [],
                        exchildNodes: [],
                        parentNode: {
                          id: "0",
                          type: "profileNode",
                          position: {
                            x: 0,
                            y: 0,
                          },
                          data: {
                            parent: true,
                            partner: true,
                            expartner: false,
                            children: 0,
                            exchildren: 0,
                            childNodes: [],
                            exchildNodes: [],
                            parentNode: {
                              id: "1",
                              type: "profileNode",
                              position: {
                                x: 150,
                                y: -380,
                              },
                              data: {
                                parent: false,
                                partner: true,
                                expartner: false,
                                children: 2,
                                exchildren: 0,
                                childNodes: [
                                  {
                                    parent: false,
                                    partner: false,
                                    expartner: false,
                                    children: 0,
                                    exchildren: 0,
                                    childNodes: [],
                                    exchildNodes: [],
                                    parentNode: [],
                                    gender: "female",
                                    position: {
                                      x: 0,
                                      y: 0,
                                    },
                                  },
                                  {
                                    id: "2",
                                    type: "profileNode",
                                    position: {
                                      x: -300,
                                      y: 0,
                                    },
                                    data: {
                                      parent: true,
                                      partner: false,
                                      expartner: false,
                                      children: 0,
                                      exchildren: 0,
                                      childNodes: [],
                                      exchildNodes: [],
                                      parentNode: [],
                                      gender: "female",
                                      position: {
                                        x: -300,
                                        y: 0,
                                      },
                                    },
                                  },
                                ],
                                exchildNodes: [],
                                parentNode: [],
                                gender: "female",
                                position: {
                                  x: 150,
                                  y: -380,
                                },
                              },
                            },
                            gender: "male",
                            position: {
                              x: 0,
                              y: 0,
                            },
                          },
                        },
                        gender: "female",
                        position: {
                          x: 150,
                          y: 380,
                        },
                      },
                    },
                    gender: "female",
                    position: {
                      x: 0,
                      y: 760,
                    },
                  },
                },
                gender: "female",
                position: {
                  x: -150,
                  y: 1140,
                },
              },
            },
            gender: "female",
            position: {
              x: -300,
              y: 1520,
            },
          },
        },
      ],
      exchildNodes: [],
      parentNode: {
        id: "4",
        type: "profileNode",
        position: {
          x: 0,
          y: 760,
        },
        data: {
          parent: true,
          partner: true,
          expartner: false,
          children: 0,
          exchildren: 0,
          childNodes: [],
          exchildNodes: [],
          parentNode: {
            id: "3",
            type: "profileNode",
            position: {
              x: 150,
              y: 380,
            },
            data: {
              parent: true,
              partner: true,
              expartner: false,
              children: 0,
              exchildren: 0,
              childNodes: [],
              exchildNodes: [],
              parentNode: {
                id: "0",
                type: "profileNode",
                position: {
                  x: 0,
                  y: 0,
                },
                data: {
                  parent: true,
                  partner: true,
                  expartner: false,
                  children: 0,
                  exchildren: 0,
                  childNodes: [],
                  exchildNodes: [],
                  parentNode: {
                    id: "1",
                    type: "profileNode",
                    position: {
                      x: 150,
                      y: -380,
                    },
                    data: {
                      parent: false,
                      partner: true,
                      expartner: false,
                      children: 2,
                      exchildren: 0,
                      childNodes: [
                        {
                          parent: false,
                          partner: false,
                          expartner: false,
                          children: 0,
                          exchildren: 0,
                          childNodes: [],
                          exchildNodes: [],
                          parentNode: [],
                          gender: "female",
                          position: {
                            x: 0,
                            y: 0,
                          },
                        },
                        {
                          id: "2",
                          type: "profileNode",
                          position: {
                            x: -300,
                            y: 0,
                          },
                          data: {
                            parent: true,
                            partner: false,
                            expartner: false,
                            children: 0,
                            exchildren: 0,
                            childNodes: [],
                            exchildNodes: [],
                            parentNode: [],
                            gender: "female",
                            position: {
                              x: -300,
                              y: 0,
                            },
                          },
                        },
                      ],
                      exchildNodes: [],
                      parentNode: [],
                      gender: "female",
                      position: {
                        x: 150,
                        y: -380,
                      },
                    },
                  },
                  gender: "male",
                  position: {
                    x: 0,
                    y: 0,
                  },
                },
              },
              gender: "female",
              position: {
                x: 150,
                y: 380,
              },
            },
          },
          gender: "female",
          position: {
            x: 0,
            y: 760,
          },
        },
      },
      gender: "female",
      position: {
        x: -150,
        y: 1140,
      },
    },
  },
  {
    id: "5-partner",
    type: "relationNode",
    position: {
      x: -450,
      y: 1140,
    },
    data: {
      gender: "male",
    },
  },
  {
    id: "6",
    type: "profileNode",
    position: {
      x: -300,
      y: 1520,
    },
    data: {
      parent: true,
      partner: false,
      expartner: false,
      children: 0,
      exchildren: 0,
      childNodes: [],
      exchildNodes: [],
      parentNode: {
        id: "5",
        type: "profileNode",
        position: {
          x: -150,
          y: 1140,
        },
        data: {
          parent: true,
          partner: true,
          expartner: false,
          children: 0,
          exchildren: 0,
          childNodes: [],
          exchildNodes: [],
          parentNode: {
            id: "4",
            type: "profileNode",
            position: {
              x: 0,
              y: 760,
            },
            data: {
              parent: true,
              partner: true,
              expartner: false,
              children: 0,
              exchildren: 0,
              childNodes: [],
              exchildNodes: [],
              parentNode: {
                id: "3",
                type: "profileNode",
                position: {
                  x: 150,
                  y: 380,
                },
                data: {
                  parent: true,
                  partner: true,
                  expartner: false,
                  children: 0,
                  exchildren: 0,
                  childNodes: [],
                  exchildNodes: [],
                  parentNode: {
                    id: "0",
                    type: "profileNode",
                    position: {
                      x: 0,
                      y: 0,
                    },
                    data: {
                      parent: true,
                      partner: true,
                      expartner: false,
                      children: 0,
                      exchildren: 0,
                      childNodes: [],
                      exchildNodes: [],
                      parentNode: {
                        id: "1",
                        type: "profileNode",
                        position: {
                          x: 150,
                          y: -380,
                        },
                        data: {
                          parent: false,
                          partner: true,
                          expartner: false,
                          children: 2,
                          exchildren: 0,
                          childNodes: [
                            {
                              parent: false,
                              partner: false,
                              expartner: false,
                              children: 0,
                              exchildren: 0,
                              childNodes: [],
                              exchildNodes: [],
                              parentNode: [],
                              gender: "female",
                              position: {
                                x: 0,
                                y: 0,
                              },
                            },
                            {
                              id: "2",
                              type: "profileNode",
                              position: {
                                x: -300,
                                y: 0,
                              },
                              data: {
                                parent: true,
                                partner: false,
                                expartner: false,
                                children: 0,
                                exchildren: 0,
                                childNodes: [],
                                exchildNodes: [],
                                parentNode: [],
                                gender: "female",
                                position: {
                                  x: -300,
                                  y: 0,
                                },
                              },
                            },
                          ],
                          exchildNodes: [],
                          parentNode: [],
                          gender: "female",
                          position: {
                            x: 150,
                            y: -380,
                          },
                        },
                      },
                      gender: "male",
                      position: {
                        x: 0,
                        y: 0,
                      },
                    },
                  },
                  gender: "female",
                  position: {
                    x: 150,
                    y: 380,
                  },
                },
              },
              gender: "female",
              position: {
                x: 0,
                y: 760,
              },
            },
          },
          gender: "female",
          position: {
            x: -150,
            y: 1140,
          },
        },
      },
      gender: "female",
      position: {
        x: -300,
        y: 1520,
      },
    },
  },
];
export const initialEdge = [
  {
    id: "e-1-0",
    type: "customEdge",
    data: "female",
    source: "1",
    target: "0",
    targetHandle: "top",
    sourceHandle: "relatives",
  },
  {
    id: "e-1-partner",
    type: "relationEdge",
    source: "1",
    target: "1-partner",
  },
  {
    id: "e-2-1",
    type: "customEdge",
    data: "female",
    source: "1",
    target: "2",
    targetHandle: "top",
    sourceHandle: "relatives",
  },
  {
    id: "e-0-partner",
    type: "relationEdge",
    source: "0",
    sourceHandle: "relatives",
    target: "0-partner",
    targetHandle: "partner",
    selected: false,
  },
  {
    id: "e-2-partner",
    type: "relationEdge",
    source: "2",
    sourceHandle: "relatives",
    target: "2-partner",
    targetHandle: "partner",
  },
  {
    id: "e-3-parent",
    type: "customEdge",
    data: "male",
    source: "0",
    target: "3",
    targetHandle: "top",
    sourceHandle: "relatives",
  },
  {
    id: "e-3-partner",
    type: "relationEdge",
    source: "3",
    sourceHandle: "relatives",
    target: "3-partner",
    targetHandle: "partner",
    selected: false,
  },
  {
    id: "e-4-parent",
    type: "customEdge",
    data: "female",
    source: "3",
    target: "4",
    targetHandle: "top",
    sourceHandle: "relatives",
  },
  {
    id: "e-4-partner",
    type: "relationEdge",
    source: "4",
    sourceHandle: "relatives",
    target: "4-partner",
    targetHandle: "partner",
    selected: false,
  },
  {
    id: "e-5-parent",
    type: "customEdge",
    data: "female",
    source: "4",
    target: "5",
    targetHandle: "top",
    sourceHandle: "relatives",
  },
  {
    id: "e-5-partner",
    type: "relationEdge",
    source: "5",
    sourceHandle: "relatives",
    target: "5-partner",
    targetHandle: "partner",
    selected: true,
  },
  {
    id: "e-6-parent",
    type: "customEdge",
    data: "female",
    source: "5",
    target: "6",
    targetHandle: "top",
    sourceHandle: "relatives",
  },
];
